[package]
name = "half_and_half"
version = "0.1.0"
authors = ["yasukotelin <31115673+yasukotelin@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
